-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON vzzorman;
DROP POLICY IF EXISTS "Enable read access for anonymous users" ON vzzorman;

-- Drop existing check constraint if it exists
ALTER TABLE IF EXISTS vzzorman DROP CONSTRAINT IF EXISTS vzzorman_pozicia_check;

-- Create or update vzzorman table
CREATE TABLE IF NOT EXISTS vzzorman (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meno TEXT NOT NULL,
    pozicia TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add check constraint
ALTER TABLE vzzorman ADD CONSTRAINT vzzorman_pozicia_check 
    CHECK (pozicia IN (
        'VZA12', 'VZB12', 'VZC12', 'VZD12',
        'ManipulantA', 'ManipulantC', 'ManipulantD', 'ManipulantO',
        'ZoradovacA12', 'ZoradovacB12', 'ZoradovacC12', 'ZoradovacD12',
        'Drvič'
    ));

-- Create index for faster searching
CREATE INDEX IF NOT EXISTS idx_vzzorman_meno ON vzzorman(meno);
CREATE INDEX IF NOT EXISTS idx_vzzorman_pozicia ON vzzorman(pozicia);

-- Add RLS (Row Level Security) policies
ALTER TABLE vzzorman ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users
CREATE POLICY "Enable all access for authenticated users" ON vzzorman
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Create policy for anonymous users (if needed)
CREATE POLICY "Enable read access for anonymous users" ON vzzorman
    FOR SELECT
    TO anon
    USING (true); 