-- Vytvorenie tabuľky normy
CREATE TABLE IF NOT EXISTS normy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazov VARCHAR(255) NOT NULL,
    skratka VARCHAR(10) NOT NULL,
    hodinova_norma DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Vytvorenie indexu pre rýchlejšie vyhľadávanie
CREATE INDEX IF NOT EXISTS idx_normy_nazov ON normy(nazov);
CREATE INDEX IF NOT EXISTS idx_normy_skratka ON normy(skratka);

-- Vytvorenie triggeru pre automatické aktualizovanie updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_normy_updated_at
    BEFORE UPDATE ON normy
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Vytvorenie RLS (Row Level Security) politiky
ALTER TABLE normy ENABLE ROW LEVEL SECURITY;

-- Vytvorenie politiky pre čítanie (SELECT)
CREATE POLICY "Povoliť čítanie noriem všetkým používateľom"
    ON normy FOR SELECT
    USING (true);

-- Vytvorenie politiky pre vkladanie (INSERT)
CREATE POLICY "Povoliť vkladanie noriem autentizovaným používateľom"
    ON normy FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

-- Vytvorenie politiky pre aktualizáciu (UPDATE)
CREATE POLICY "Povoliť aktualizáciu noriem autentizovaným používateľom"
    ON normy FOR UPDATE
    USING (auth.role() = 'authenticated');

-- Vytvorenie politiky pre mazanie (DELETE)
CREATE POLICY "Povoliť mazanie noriem autentizovaným používateľom"
    ON normy FOR DELETE
    USING (auth.role() = 'authenticated'); 